# Generated by Django 5.0.14 on 2026-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
