# Generated by Django 6.0.4 on 2026-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('herb', 'Herb'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('medicinal', 'Medicinal'), ('flowering', 'Flowering')], max_length=20)),
                ('is_edible', models.BooleanField(default=False)),
                ('sunlight', models.CharField(max_length=100)),
                ('water_needs', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
