# Generated by Django 5.0.14 on 2026-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_remove_category_color_remove_category_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Country Name"
                    ),
                ),
                (
                    "flag",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Flag Image URL"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="plants",
                to="plants.country",
                verbose_name="Native Countries",
            ),
        ),
    ]
