# Generated by Django 5.0.14 on 2026-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0003_alter_comment_options_alter_comment_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plant",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
            },
        ),
        migrations.AlterField(
            model_name="plant",
            name="category",
            field=models.CharField(
                choices=[
                    ("indoor", "Indoor"),
                    ("outdoor", "Outdoor"),
                    ("herb", "Herb"),
                    ("fruit", "Fruit"),
                    ("vegetable", "Vegetable"),
                    ("medicinal", "Medicinal"),
                    ("flowering", "Flowering"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="image_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="plant",
            name="is_edible",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="plant",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["plant", "-created_at"], name="plants_comm_plant_i_574d5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(
                fields=["-created_at", "category"],
                name="plants_plan_created_c3e580_idx",
            ),
        ),
    ]
