# Generated by Django 5.0.14 on 2026-04-20 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0004_alter_plant_options_alter_plant_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="plant",
            index=models.Index(
                fields=["-views_count"], name="plants_plan_views_c_e4d8c0_idx"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="plants.plant",
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["plant", "-created_at"], name="plants_rati_plant_i_85e7a3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("plant", "name")},
        ),
    ]
